### ISSUE TITLE
Readme: Xkcd vs xkcd

### ISSUE THREAD

**Issue by stsievert** [mgajda/wordpass#1]
The [xkcd about](http://xkcd.com/about/) page says

> ##### How do I write "xkcd"? There's nothing in Strunk and White about this.
> 
> For those of us pedantic enough to want a rule, here it is: The preferred form is "xkcd", all lower-case. In formal contexts where a lowercase word shouldn't start a sentence, "XKCD" is an okay alternative. "Xkcd" is frowned upon.

But the readme says "Inspired by Xkcd comic." A small issue not worth a pull request, but I would suggest changing it to "Inspired by this xkcd comic."

**Comment by mgajda** [comment]
Ok, will fix :+1:
